include: package:all_lint_rules_community/all.yaml

analyzer:
  plugins:
    - custom_lint

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: ignore

  exclude:
    - "**.g.dart"

linter:
  rules:
    unnecessary_final: false
    one_member_abstracts: false
    always_specify_types: false
    prefer_double_quotes: false
    sort_pub_dependencies: false
    public_member_api_docs: false
    prefer_final_parameters: false
    always_use_package_imports: false
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: false
    diagnostic_describe_all_properties: false
    always_put_control_body_on_new_line: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
    always_put_required_named_parameters_first: false
