name: gallery_camera_image_picker_view
description: A complete widget from which can easily take image from camera & pick multiple images from device and display them in UI. Also images can be re-ordered and removed easily.
version: 0.0.2
homepage: https://github.com/bruhankhanzada/gallery_camera_image_picker_view
repository: https://github.com/bruhankhanzada/gallery_camera_image_picker_view
issue_tracker: https://github.com/bruhankhanzada/gallery_camera_image_picker_view/issues

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_view: ^0.14.0
  image_picker: ^1.0.1
  mobkit_dashed_border: ^0.0.5
  flutter_reorderable_grid_view: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.31
